#! /bin/bash
broadcast=$(ip a | grep -o '[0-9]\{0,3\}\.[0-9]\{0,3\}\.[0-9]\{0,3\}\.255' | uniq)

RED='\033[0;31m'
GRAY='\033[0;37m'
GREEN='\033[0;32m'
NC='\033[0m'

clear
printf "${GRAY}Executing nmap on the subnets: ${RED}\n$broadcast\n"
candidates=$(
for brdip in ${broadcast}; do 
	nmap -sP $brdip/24 | grep -o '[0-9]\{0,3\}\.[0-9]\{0,3\}\.[0-9]\{0,3\}\.[2-9][0-9]\{0,2\}' | uniq
done)
printf "${GRAY}\nFound the following candidates: ${GREEN}\n$candidates\n"
for ip in ${candidates}; do
	printf "${GRAY}\nProbing $ip...\n${NC}"
	ssh -q root@$ip
done
clear
echo "Nothing found"
